config/routes.rb
CollectiveThinking::Application.routes.draw do
  namespace :users do
    resources :collections
  end

  devise_for :users

  root to: 'static_pages#home'
  match 'about', to: 'static_pages#about', via: :get
  match 'contact', to:'static_pages#contact', via: :get
  match 'groups', to: 'static_pages#groups', via: :get

  

end

app/models/group.rb
class Group < ActiveRecord::Base
   has_many :memberships
   has_many :users, through: :memberships
   attr_accessible :title, :description, :isPublic
end

app/models/memberships.rb
class Memberships < ActiveRecord::Base
	belongs_to :group
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/users.rb
module Users
  def self.table_name_prefix
    'users_'
  end
  
end

app/models/users/collection.rb
class Users::Collection < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def groups
  end
end

app/controllers/users/collections_controller.rb
class Users::CollectionsController < ApplicationController
  before_action :set_users_collection, only: [:show, :edit, :update, :destroy]
  
  # GET /users/collections
  # GET /users/collections.json
  def index
    @users_collections = Users::Collection.all
  end

  # GET /users/collections/1
  # GET /users/collections/1.json
  def show
  end

  # GET /users/collections/new
  def new
    @users_collection = Users::Collection.new
  end

  # GET /users/collections/1/edit
  def edit
  end

  # POST /users/collections
  # POST /users/collections.json
  def create
    @users_collection = Users::Collection.new(users_collection_params)

    respond_to do |format|
      if @users_collection.save
        format.html { redirect_to @users_collection, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @users_collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @users_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/collections/1
  # PATCH/PUT /users/collections/1.json
  def update
    respond_to do |format|
      if @users_collection.update(users_collection_params)
        format.html { redirect_to @users_collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @users_collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/collections/1
  # DELETE /users/collections/1.json
  def destroy
    @users_collection.destroy
    respond_to do |format|
      format.html { redirect_to users_collections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_users_collection
      @users_collection = Users::Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def users_collection_params
      params.require(:users_collection).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users/collections_helper.rb
module Users::CollectionsHelper
end

app/views/layouts/_header.html.erb
<nav class="text-center navbar navbar-fixed-top navbar-inverse" style="margin-bottom:0px;" >
 <nav class="menu" style="margin-bottom:0px;">
  <a href="/" class="btn btn-info btn-lg" style="background-color:Silver;" >Home</a> |

  <a href="/about" class="btn btn-info btn-lg" style="background-color:Silver;">About</a> |
  
  <a href="/contact" class="btn btn-info btn-lg" style="background-color:Silver;" >Contact</a> |
  
  <a href="/groups" class="btn btn-info btn-lg" style="background-color:Silver;" >Groups </a>
</nav>
</nav> 

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top" >
  <div class="container">
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Collective Thinking" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Collective Thinking" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
    <header >
  <!--    <%= render 'layouts/navigation' %> -->
      <%= render 'layouts/header' %> 
    </header>
  
    <main role="main">
       <%= render 'layouts/messages' %>
        <p class="navbar-text pull-right">
       <% if user_signed_in? %>
             Logged in as <strong><%= current_user.email %></strong>.

        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
         <% end %>
       
       <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
       

<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>
       <%= yield %>
    </main>

  </body>
</html>

app/views/static_pages/about.html.erb
<h1>Hi there!</h1>

<p> Log in and you can start your own study group with people around the world. </p>
 

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/groups.html.erb
<h1>StaticPages#groups</h1>
<p>Find me in app/views/static_pages/groups.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Hi there!</h1>

<p> Log in and you can start your own study group with people around the world. </p>
 

app/views/users/collections/_form.html.erb
<%= form_for(@users_collection) do |f| %>
  <% if @users_collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@users_collection.errors.count, "error") %> prohibited this users_collection from being saved:</h2>

      <ul>
      <% @users_collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/collections/edit.html.erb
<h1>Editing users_collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @users_collection %> |
<%= link_to 'Back', users_collections_path %>

app/views/users/collections/index.html.erb
<h1>Your collections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users_collections.each do |users_collection| %>
      <tr>
        <td><%= users_collection.title %></td>
        <td><%= users_collection.description %></td>
        <td><%= link_to 'Show', users_collection %></td>
        <td><%= link_to 'Edit', edit_users_collection_path(users_collection) %></td>
        <td><%= link_to 'Destroy', users_collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_users_collection_path %>

app/views/users/collections/new.html.erb
<h1>New users_collection</h1>

<%= render 'form' %>

<%= link_to 'Back', users_collections_path %>

app/views/users/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @users_collection.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @users_collection.description %>
</p>

<%= link_to 'Edit', edit_users_collection_path(@users_collection) %> |
<%= link_to 'Back', users_collections_path %>